### ISSUE TITLE
Images in list view website don't resize properly

### ISSUE THREAD

**Issue by jeffb4real** [jeffb4real/SLHPA-Web-App#2]
# Description
<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/22355779/52459673-6b8c9f00-2b1b-11e9-9e27-10c562c5116b.png">
Images will appear full-size instead of being resized to 20%.
This bug was observed on these platforms/browsers:

* Mac: Firefox Quantum v65.0 (64-bit)
* PC: Firefox, Edge

This bug was *not* observed on these platforms/browsers:

* Mac: Chrome, Safari
* PC: Chrome

# To reproduce

1. git pull: 47bdfc85be71d23b6ea96add57b3d4314cfb9d71
2. Launch a provisioned environment (see README.md)
3. run Django web server
4. build database: http://127.0.0.1:8000/slhpa/transformed.csv
5. load website: http://127.0.0.1:8000/slhpa

# Expected behavior

Images should be resized to 20% of original size on all modern platforms/browsers.

**Comment by chrisxkeith** [comment]
First failed attempt to fix:
$ git diff
diff --git a/mysite/slhpa/templates/slhpa/index.html b/mysite/slhpa/templates/slhpa/index.html
index 31aebe7..ac89334 100644
--- a/mysite/slhpa/templates/slhpa/index.html
+++ b/mysite/slhpa/templates/slhpa/index.html
@@ -62,7 +62,7 @@
                     {% static "/slhpa/images/photos" as baseUrl %}
                     <a href="{{ photo.url_for_file }}">
                         <div>
-                            <img id="main_img" src="{{ baseUrl }}/{{ photo.resource_name }}.jpg" height="20%" border="2">
+                            <img id="main_img" src="{{ baseUrl }}/{{ photo.resource_name }}.jpg" height="20%" max-height="20%" border="2">
                             <img id="overlay_img" src="{{ baseUrl }}/finger.png" height="8%">

https://support.mozilla.org/en-US/questions/1035766

**Comment by chrisxkeith** [comment]
Notes : https://docs.google.com/document/d/1RCfsPWKOrvhG69kthQkqnh1OpCWR-_5zgphCh2zkdHE/edit

**Comment by jeffb4real** [comment]
Fixed in commit 8dcdb85b1222914763814ce1b190603432391b3a
Replaced `img` attribute `height` with `width`, which causes both Chrome and Firefox (both MacOS) to correctly resize photo thumbnails. Not sure why this works, [the doc I read](https://www.w3schools.com/tags/tag_img.asp) doesn't mention using height or width separately.
