### ISSUE TITLE
Four records have no resource_name

### ISSUE THREAD

**Issue by jeffb4real** [jeffb4real/SLHPA-Web-App#5]
When photo records are imported from .csv (via http://127.0.0.1:8000/slhpa/import/transformed) it was noticed that four records have no resource_name:

> Added 2526 records from /Users/urieow/mygithub/SLHPA-Web-App/mysite/slhpa/static/slhpa/data/transformed.csv, exceptions: 0, no_resource: 4, no_key: 0, seconds: 1, rows_in_table: 2526

To reproduce:
1. pull 7184ced992ef9499e3347e132f7fabf756a014d3
2. view transformed.csv to see four instances where resource_name field is empty:
<img width="258" alt="Screen Shot 2019-04-10 at 7 11 49 AM" src="https://user-images.githubusercontent.com/22355779/55886172-1ba07780-5b60-11e9-82fc-a8b48ad1bcf2.png">
<img width="252" alt="Screen Shot 2019-04-10 at 7 11 34 AM" src="https://user-images.githubusercontent.com/22355779/55886174-1ba07780-5b60-11e9-827d-6ae46e088d85.png">
<img width="247" alt="Screen Shot 2019-04-10 at 7 11 10 AM" src="https://user-images.githubusercontent.com/22355779/55886176-1c390e00-5b60-11e9-9cc7-64d7f201d669.png">
<img width="301" alt="Screen Shot 2019-04-10 at 7 10 49 AM" src="https://user-images.githubusercontent.com/22355779/55886177-1c390e00-5b60-11e9-97db-2924b73dc64c.png">

**Comment by chrisxkeith** [comment]
Four records from transcribed.csv do not have corresponding entries in scraped.csv:

> No resource_name for: 00000128.pdf : OrderedDict([('resource_number', '128'), ('year', '1920'), ('geo_coord_original', '10D825'), ('paper_page_number', '116'), ('source_index', 'S')])No resource_name for: 00001306.pdf : OrderedDict([('resource_number', '1306'), ('year', '1916'), ('geo_coord_original', '15D625'), ('paper_page_number', '101'), ('source_index', 'S')])
> No resource_name for: 00001347.pdf : OrderedDict([('resource_number', '1347'), ('year', '1880'), ('geo_coord_original', '28D824'), ('paper_page_number', '98'), ('source_index', 'S')])No resource_name for: 00001775.pdf : OrderedDict([('resource_number', '1775'), ('year', '1910'), ('geo_coord_original', '24D621'), ('paper_page_number', '43'), ('source_index', 'S')])
